# This file is for custom makefile targets at the project level.
# They are meant to be share by the whole project team.

## -- Project targets ----------------------------------------------------------------------------------------------- ##

.PHONY: custom-target-example
custom-target-example: ## Example custom target
	@echo The name of the package contained in this repository is [$(APPLICATION_NAME)]

.PHONY: install-notebook
install-notebook: poetry-install-auto _check-env ## Install the application along with notebook dependencies
	@$(POETRY_COMMAND) install --with notebook
	@make -s _remind-env-activate