dataset:
  visualize: True # general
  original_mosaic_dataset: True # indicates if you are working with the original mosaic dataset
  ignore_unlabelled: True # general
  sample_size_unlabelled: 1000 # general
  tsne: 0 #adapt to number of dimensions you would like to reduce to # general
  k_fold: 5 # cross_validation
  test_size: 0.2 # splitter
  train_size: 0.8 # splitter 
profile:
  sum_mm: 1
  gradient: True
  window_size: 
    - 4 
    - 12
  window_type: gaussian
  window_type_std: 1
  rolling_cols: 
    - mean_force
    - var_force
    - min_force
    - max_force
  poisson_cols: 
    - median_force
    - lambda
    - delta
    - L
