params:
  sum_mm: 1
  gradient: True
  window_size: 
  - 4 
  - 12
  window_type: gaussian
  window_type_std: 1
  rolling_cols: 
  - mean_force
  - var_force
  - min_force
  - max_force
  poisson_cols: 
  - median_force
  - lambda
  - delta
  - L
