plots:
  normalize:
    balanced_dataset: True
    pairwise_features: True
    correlation_heatmap_all_features: True
    correlation_heatmap_between_features: True
    anova: True
    random_forest_feature_extraction: True
    smp_features: True
    bog_plot: True
    all_in_one_plot: True
    pca: True
    tsne: True
    tsne_pca: True
  original:
    pairwise_features: True
    correlation_heatmap: True
    anova: True
    one_unlabelled_smp: True
    one_labelled_smp: True
    smp_features: True
    bog_plot: True
    all_in_one_plot: True
  results:
    roc_auc: True
    bog_plot: True
    cf_matrix: True
    comparison: True
  
