random_seed: 42
run: # best is to just set one to true
  preprocess: True
  train: False
  validate: False
  test: False
  predict: False
  tune: False
raw_data: # this can come from anywhere in your system
  smp: /home/julia/Documents/University/BA/Data/Arctic_updated/
  temperature: /home/julia/Documents/University/BA/Data/Arctic/MOSAiC_ICE_Temperature.csv
processed_data: # this is all expected to live in the snowdragon root dir
   preprocessed_data: /data/tsne_project/tsne_preprocess_k5.txt
   exported_smp_files:  /data/smp_profiles
   normalized_npz_file: /data/tsne_project/tsne_smp_profiles_normalized.npz
   npz_file: /data/tsne_project/tsne_smp_profiles.npz
   evaluation: /output/evaluation/
models: # the models you would like to run
  - baseline
  - kmeans
  - gmm
  - bmm
  - label_spreading
  - self_trainer
  - rf
  - svm
  - knn
  - easy_ensemble
  - lstm
  - blstm
  - enc_dec
configs:
  colors: colors.yaml
  graintypes: graintypes.yaml
  model_params: model_params.yaml
  names: names.yaml
  plots: plots.yaml
  preprocessing: preprocessing.yaml
  smp_devices: smp_devices.yaml
  
#TODO add seed and name of this run


