# TODO include all the other configs here

# TODO include the data paths here

# TODO include what you are running here

# models that you want to run

# preprocess 
# evaluate
# train and store 
# validate